repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: autopep8-wrapper
      args:
        - --in-place
        - --max-line-length=99
        - --ignore=E402,W503
    - id: flake8
      args:
        - --max-line-length=99
        - --ignore=E402,W503
    - id: check-ast
    - id: check-case-conflict
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
# We run pylint from local env, to ensure modules can be found
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: python -m pylint.__main__
      language: system
      types: [python]
      args:
        - --disable=broad-except
        - --disable=duplicate-code
        - --disable=invalid-name
        - --disable=missing-docstring
        - --disable=no-self-use
        - --disable=protected-access
        - --disable=too-few-public-methods
        - --disable=too-many-arguments
        - --disable=too-many-branches
        - --disable=too-many-lines
        - --disable=too-many-locals
        - --disable=too-many-public-methods
        - --disable=too-many-statements
        - --disable=ungrouped-imports
        - --disable=wrong-import-order
        - --disable=wrong-import-position
        - --include-naming-hint=yes
        - --max-args=10
        - --max-line-length=99
        - --max-locals=25
        - --max-returns=10
