# We run pylint from local env, to ensure modules can be found
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: python -m pylint.__main__
      language: system
      types: [python]
      args:
        - --include-naming-hint=yes
        - --disable=duplicate-code
        - --disable=missing-docstring
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    python_version: python3.6
    args:
      - --line-length=99
