version: 2
jobs:
  build:
    docker:
      - image: python:3.8.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install .
            pip install pre-commit pylint
            pre-commit install --install-hooks
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run linting
          command: pre-commit run --all-files
      - run:
          name: Run tests
          command: |
            set -xu
            ./cc-test-reporter before-build
            ./test.sh
            coverage combine
            coverage xml
            ./cc-test-reporter after-build --exit-code $?
